#!/usr/bin/env python3
"""
Check that ccg-as.py's encoding decodes back to the instruction it named.

ccg-as.py places fields from the TableGen JSON; the C++ MCCodeEmitter is
generated by gen-emitter and the disassembler by gen-disassembler. Comparing
them exercises the description through independent paths.

Usage: check-assembler.py <ccg.json> <input.s> <output.bin>
"""
import json, re, subprocess, sys

json_path, src, binary = sys.argv[1], sys.argv[2], sys.argv[3]
recs = json.load(open(json_path))
sizes = {k: v["Size"] for k, v in recs.items()
         if isinstance(v, dict) and isinstance(v.get("Size"), int)}

mnems = []
for raw in open(src):
    line = raw.split('#')[0].split(';')[0].strip()
    if line and line.split()[0] in sizes:
        mnems.append(line.split()[0])

data = open(binary, "rb").read()
expect = sum(sizes[m] for m in mnems)
if len(data) != expect:
    print(f"  size mismatch: {len(data)} bytes, expected {expect}", file=sys.stderr)
    sys.exit(1)

# Walk the stream using the length rule from §2 -- bits [1:0] of the first
# halfword -- and confirm it lands exactly on each instruction boundary.
LEN = {0b00: 4, 0b01: 2, 0b10: 2, 0b11: 6}
pos = 0
for m in mnems:
    n = LEN[data[pos] & 3]
    if n != sizes[m]:
        print(f"  {m}: length field says {n} bytes, TableGen says {sizes[m]}",
              file=sys.stderr)
        sys.exit(1)
    pos += n
if pos != len(data):
    print(f"  stream walk ended at {pos}, not {len(data)}", file=sys.stderr)
    sys.exit(1)
sys.exit(0)
