#!/usr/bin/env python3
"""Assemble docs/walkthrough.md from the generated artifacts."""
import re, subprocess, pathlib
W = pathlib.Path("docs/walkthrough")

def fn_body(path):
    return re.search(r'^define.*?^}', open(path).read(), re.S | re.M).group(0).rstrip()

run = lambda *a: subprocess.run(a, capture_output=True, text=True).stdout.rstrip()
src      = open("test/cuda/vadd-aligned.cu").read().rstrip()
clang_ir = fn_body(W/"2-clang.ll")
low_ir   = fn_body(W/"3-lowered.ll")
asm      = "\n".join(l for l in open(W/"4-asm.s").read().splitlines()
                     if not re.match(r'^\s*\.[a-z]', l) and l.strip())
hexd     = open(W/"5-hexdump.txt").read().rstrip()
dec_por  = run("python3","tools/decode-one.py","build/generated/CCV.json",str(W/"5-text.bin"),"0x16")
dec_f48  = run("python3","tools/decode-one.py","build/generated/CCV.json",str(W/"5-text.bin"),"0x0")
trace    = "\n".join(l for l in open(W/"6-trace.txt").read().splitlines()
                     if re.match(r'^\s+[0-9a-f]{4}\s', l))
e2e      = run("./tools/run-e2e.sh")
def body_of(path, label="LBB0_1"):
    """The loop body of a listing: the label through its backward branch."""
    out, inside = [], False
    for l in open(path).read().splitlines():
        if l.startswith(label + ":"):
            inside = True
        if inside and l.strip() and not re.match(r'^\s*\.[a-z]', l):
            out.append(l)
        if inside and re.search(r'bra\s+' + label + r'\s*$', l):
            break
    return "\n".join(out)

def listing(path):
    return "\n".join(l for l in open(path).read().splitlines()
                      if not re.match(r'^\s*\.[a-z]', l) and l.strip())

def count_chwidth(text):
    return len([l for l in text.splitlines() if re.match(r'\s*chwidth', l)])

narrow_asm    = listing(W/"8-narrow-asm.s")
narrow_body   = body_of(W/"8-narrow-asm.s")
wide_body     = body_of(W/"8-wide-asm.s")
noedge_body   = body_of(W/"8-narrow-asm-noedge.s")
unal_body     = body_of(W/"8-narrow-asm-unaligned.s")
chw_stats     = open(W/"8-chwidth-stats.txt").read().rstrip()
narrow_src    = open("test/bench/vadd16_loop.cu").read().rstrip()
nb_n, nb_w    = len(narrow_body.splitlines()) - 1, len(wide_body.splitlines()) - 1
nb_noedge     = len(noedge_body.splitlines()) - 1

SPEC = "docs/isa-v1.6-operation-map-and-encoding.md"
prov     = run("python3","tools/check-spec-vs-codegen.py", SPEC, "5.6", str(W/"4-asm.s"))
prov55   = run("python3","tools/check-spec-vs-codegen.py", SPEC, "5.5",
               str(W/"4-asm-unaligned.s"))
asm_un   = "\n".join(l for l in open(W/"4-asm-unaligned.s").read().splitlines()
                     if not re.match(r'^\s*\.[a-z]', l) and l.strip())
nbytes = (W/"5-text.bin").stat().st_size
ninstr = len([l for l in hexd.splitlines() if l.startswith("0x")])

doc = f"""# Walkthrough — one kernel, source to execution

A complete trace of the pipeline for a kernel that works today. Every listing is
generated by `tools/make-walkthrough.sh`; nothing here is transcribed.

```
vadd.cu → clang → NVVM IR → CCVLowerKernelArgs → ccv-llc → ELF
        → .text → ccv-sim
```

---

## 1. The kernel

```cuda
{src}
```

`align_value(65536)` is O-23's per-argument alignment attribute — the only
target-specific thing in this source. It is an optimisation, not a requirement:
the unaligned shape compiles too, and §4 below shows what it costs. Codegen
once rejected it with a diagnostic, because folding the in-window offset needs a
fourth addend against a three-input AGU; `matchBaseIdx` now folds
`roffset + (i << scale)` into one index register with scale-enable clear,
trading O-7's scaling for the addend (F-27).

## 2. clang, unmodified

No CUDA toolkit is installed. `-nocudainc -nocudalib` skip the SDK and
libdevice; `threadIdx` and friends come from clang's own
`__clang_cuda_builtin_vars.h`.

```llvm
{clang_ir}
```

Three things the backend is built around: the
`llvm.nvvm.read.ptx.sreg.{{tid,ctaid,ntid}}.x` intrinsics, which ISA §5.3 divides
between the launch block and `srd`; `getelementptr inbounds`, the guarantee that
makes the windowed address model work; and the `!nvvm.annotations … "kernel"`
marker, which is how the ABI pass finds kernels without the frontend being
modified.

## 3. Kernel ABI lowering

```llvm
{low_ir}
```

The kernel now takes **no parameters at all** — they arrive in the launch block
(§5.2), so the signature says so.

And the payoff of doing this in IR rather than the backend: each pointer is
`(zext rbase << 16)` with **no `add`**. The in-window offset was a constant zero
because the argument is aligned, so the optimiser folded it away. O-23's
one-register form arrives from `instcombine`, not from a backend special case.

## 4. Native assembly

```
{asm}
```

| | |
|---|---|
| `movi r0, 2` | Format F's 48-bit form materialises the launch window in one instruction |
| `ld.global r1, [r0]` | `blockDim.x` — launch-*time* data, so the block supplies it (§5.3). A zero displacement means this is Format **K**'s memory form, 16 bits rather than 32: `rd` and `rbase` sit in separate 4-bit fields, so unlike the rest of Format K there is no tie to satisfy and the rewrite is unconditional. F-111's audit found the encoding defined and unreachable |
| `srd r2, 0` / `srd r3, 1` | thread and CTA identity — the only values no memory location can supply |
| `mad.lo r1, r3, r1, r2` | the three-source form takes `ctaid*ntid + tid` in one instruction |
| `setp.le p0, r2, r1` | Format C″ (O-32), the **unpredicated** compare. Earlier revisions had no such form: Formats C/C′ carry a mandatory qualifier, so every compare had to be preceded by a `por` manufacturing a true predicate (O-24). That cost one instruction per compare — 13% of dynamically issued instructions in the reduction kernels — and is now zero |
| `@p0 bra LBB0_2` | the guard branches *over* the body, so the fall-through path has no branch at all |
| `[r2, r1, 1, 0]` | Format D base+index with **scale-enable set**: the AGU supplies the `chwidth`-derived shift. O-7 only fires like this for aligned pointers |
| `fadd r3, r2` | the compressed destructive form, 16 bits, because `rd == rs0` fell out naturally |

There is **no branch on the fall-through path** — the guard branches over the
body and the body falls into the exit. An earlier version emitted an explicit
`bra` to the next instruction, because the target had no branch-analysis hooks
and the generic folder could not act (F-26).

### This listing is checked against the spec

```
{prov}
```

ISA §5.6's worked listing is compared against this output on every build. That
check exists because the spec's listings were hand-written and drifted: an extra
branch and a pessimistic register count both passed the internal-consistency
checker, which by construction could not notice.

### The same kernel without the alignment attribute

`test/cuda/vadd.cu` is the same source with the alignment attribute removed. Each
pointer then occupies two launch-block slots, and the in-window offset has to be
folded into the index — a fourth addend the three-input AGU cannot take — so
scale-enable stays clear and the index carries bytes rather than elements:

```
{asm_un}
```

```
{prov55}
```

Seven more instructions and 176 more bits for the same arithmetic, which is what
the per-argument alignment attribute of O-23 buys. Note `add r1, r2, r1`: the
same fold as the two above it, at 32 bits instead of 16, because the selector
landed on `rd != rs0` and nothing tries to prevent that (F-29).

## 5. The binary

{ninstr} instructions in {nbytes} bytes. Each length comes from bits `[1:0]` of
its first halfword alone — this walker never looks at the format tag, which is
exactly what §2 claims.

```
{hexd}
```

{nbytes} bytes against {ninstr * 4} for a fixed-32 encoding.

### Two instructions, field by field

The O-24 bootstrap, decoded from the real bytes using the §3 bit map:

```
{dec_por}
```

`ps0 = 4` is `!P0` — bit 2 of a qualifier is the negate bit — and `ps1 = 0` is
`P0`. So this is `por p0, !p0, p0`: all-ones whatever `P0` held, in 16 bits.

And the 48-bit constant:

```
{dec_f48}
```

## 6. Disassembly and execution

The simulator drives the *generated* disassembler, so this is the encoding read
back by a different TableGen backend than the one that wrote it. This run has
20 of 32 threads active, so the guard actually diverges. The mask column is the
set of lanes issuing together.

```
{trace}
```

The mask is `ffffffff` through the prologue, narrows to `000fffff` for the body,
and is `ffffffff` again at `exit`. Lanes regroup because their PCs coincide —
there is no bracket instruction and nothing forces it (§1).

## 7. Result

```
{e2e}
```

`c[i] = a[i] + b[i]` verified as FP32 bit patterns across all 32 lanes at four
divergence levels. Inactive lanes are checked to be *untouched*: `c[]` is
poisoned before each run, so a lane that executed when it should not have would
fail rather than coincidentally agree.

`n=0` is the case where every lane takes the guard and the body is skipped, which
is why its issue-group count is lower.

---

## 8. Element width, and where the mode switches go

Everything above is 32-bit. §1's invariant 1 makes element width **per-logical-
register state** rather than an instruction field, so a narrow kernel is the
same instructions against a narrower slice — and somebody has to set the mode.
This section is that path end to end, because it is where the compiler can give
the whole feature away and did.

The kernel is `vadd_loop` at half the element width, so the pair differs in
nothing but width:

```cuda
{narrow_src}
```

### The mode switches are not in the loop

```
{narrow_body}
```

Against the fp32 kernel's body, which is the control:

```
{wide_body}
```

**{nb_n} instructions against {nb_w}** — the same, and not a `chwidth` among
them. Every width transition is in the preheader, executed once per thread,
where it belongs: the width is loop-invariant, so paying for it per iteration is
pure waste. The pass's own account:

```
{chw_stats}
```

`placed on an edge` is the line that matters. Where predecessors disagree about
a register's width — a preheader supplying 32 and a back-edge supplying 16 — the
transition goes on the **incoming edges**, not at the first access inside the
block. Three conditions guard it: no back-edge may need the insert, or the
instruction has only moved from the top of the loop to the bottom; the register
must be dead on the predecessor's other edges, because a terminator's `chwidth`
runs whichever way the branch goes; and it is placed before the first terminator
so the width holds on every path out.

Turning that placement off (`-ccv-chwidth-cross-block=false`) puts it back:

```
{noedge_body}
```

{nb_noedge} instructions, and the transition re-executes on every iteration.

### Two registers, two widths, one file

The unaligned form of the same kernel is where the **allocator** decides the
outcome:

```
{unal_body}
```

Also clean, and it was not always. The in-window offset has to be folded into
the index, so this body does 32-bit address arithmetic *and* 16-bit data — and
O-39 lets a load's `rdata` share a register with its `rbase`/`rindex`, because
the address read takes all 32 bits whatever the narrowing left. That saves a
register and costs a width change per iteration, which no placement pass can
lift out: the width genuinely changes inside the body.

The allocator is the only pass that can prevent the handover, and **the register
class is the only width information it has** — `chwidth` names physical
registers, so width is otherwise entirely a post-RA concept. So `GPR16`
allocates **descending** where `GPR` allocates ascending: the same sixteen
registers, opposite preference, 32-bit values clustering from `r0` up and 16-bit
from `r14` down. Under low pressure they never meet and there is no handover to
pay for; under pressure they meet in the middle and share exactly as before.

That is why the narrow data above is in `r14`/`r13` while the addresses stay low.

### What the mode switch costs when it is right

```
{narrow_asm}
```

One `chwidth.multi` for the whole kernel. O-6 gave Format I a register mask so
that a kernel entering a packed section collapses N drain events into one, and
it fires here because width affinity put the two narrow registers next to each
other — their transitions are adjacent, so they merge. An earlier measurement of
this kernel found the merge firing **zero** times and concluded the kernel shape
was wrong for it; the shape was right and the allocation was wrong.

"""
open("docs/walkthrough.md","w").write(doc)
print(f"  wrote docs/walkthrough.md ({len(doc.splitlines())} lines)")
