#!/usr/bin/env python3
"""Assemble docs/walkthrough.md from the generated artifacts."""
import re, subprocess, pathlib
W = pathlib.Path("docs/walkthrough")

def fn_body(path):
    return re.search(r'^define.*?^}', open(path).read(), re.S | re.M).group(0).rstrip()

run = lambda *a: subprocess.run(a, capture_output=True, text=True).stdout.rstrip()
src      = open("test/cuda/vadd-aligned.cu").read().rstrip()
clang_ir = fn_body(W/"2-clang.ll")
low_ir   = fn_body(W/"3-lowered.ll")
asm      = "\n".join(l for l in open(W/"4-asm.s").read().splitlines()
                     if not re.match(r'^\s*\.[a-z]', l) and l.strip())
hexd     = open(W/"5-hexdump.txt").read().rstrip()
dec_por  = run("python3","tools/decode-one.py","build/generated/CCG.json",str(W/"5-text.bin"),"0x16")
dec_f48  = run("python3","tools/decode-one.py","build/generated/CCG.json",str(W/"5-text.bin"),"0x0")
trace    = "\n".join(l for l in open(W/"6-trace.txt").read().splitlines()
                     if re.match(r'^\s+[0-9a-f]{4}\s', l))
e2e      = run("./tools/run-e2e.sh")
prov     = run("python3","tools/check-spec-vs-codegen.py",
               "docs/isa-v1.5-operation-map-and-encoding.md", str(W/"4-asm.s"))
nbytes = (W/"5-text.bin").stat().st_size
ninstr = len([l for l in hexd.splitlines() if l.startswith("0x")])

doc = f"""# Walkthrough — one kernel, source to execution

A complete trace of the pipeline for a kernel that works today. Every listing is
generated by `tools/make-walkthrough.sh`; nothing here is transcribed.

```
vadd.cu → clang → NVVM IR → CCGLowerKernelArgs → ccg-llc → ELF
        → .text → ccg-sim
```

---

## 1. The kernel

```cuda
{src}
```

`align_value(65536)` is O-23's per-argument alignment attribute — the only
target-specific thing in this source. It is not optional today: codegen does not
yet implement the unaligned shape, which needs four addends against a
three-input AGU, and rejects it with a diagnostic (F-27).

## 2. clang, unmodified

No CUDA toolkit is installed. `-nocudainc -nocudalib` skip the SDK and
libdevice; `threadIdx` and friends come from clang's own
`__clang_cuda_builtin_vars.h`.

```llvm
{clang_ir}
```

Three things the backend is built around: the
`llvm.nvvm.read.ptx.sreg.{{tid,ctaid,ntid}}.x` intrinsics, which ISA §5.3 divides
between the launch block and `srd`; `getelementptr inbounds`, the guarantee that
makes the windowed address model work; and the `!nvvm.annotations … "kernel"`
marker, which is how the ABI pass finds kernels without the frontend being
modified.

## 3. Kernel ABI lowering

```llvm
{low_ir}
```

The kernel now takes **no parameters at all** — they arrive in the launch block
(§5.2), so the signature says so.

And the payoff of doing this in IR rather than the backend: each pointer is
`(zext rbase << 16)` with **no `add`**. The in-window offset was a constant zero
because the argument is aligned, so the optimiser folded it away. O-23's
one-register form arrives from `instcombine`, not from a backend special case.

## 4. Native assembly

```
{asm}
```

| | |
|---|---|
| `f48 r0, 2` | Format F's 48-bit form materialises the launch window in one instruction |
| `ld.global r1, [r0 + 0]` | `blockDim.x` — launch-*time* data, so the block supplies it (§5.3) |
| `srd r2, 0` / `srd r3, 1` | thread and CTA identity — the only values no memory location can supply |
| `mad.lo r1, r3, r1, r2` | the three-source form takes `ctaid*ntid + tid` in one instruction |
| `por p0, 4, 0` | O-24: Formats C/C′ carry a *mandatory* qualifier and there is no unpredicated compare, so a kernel must manufacture a true predicate. Compressed forms are never predicated, which breaks the cycle |
| `@p0 setp.le p0, r2, r1` | self-guarding — guard and destination are the same predicate, so the effective file stays at four |
| `[r2, r1, 1, 0]` | Format D base+index with **scale-enable set**: the AGU supplies the `chwidth`-derived shift. O-7 only fires like this for aligned pointers |
| `fadd r3, r2` | the compressed destructive form, 16 bits, because `rd == rs0` fell out naturally |

There is **no branch on the fall-through path** — the guard branches over the
body and the body falls into the exit. An earlier version emitted an explicit
`bra` to the next instruction, because the target had no branch-analysis hooks
and the generic folder could not act (F-26).

### This listing is checked against the spec

```
{prov}
```

ISA §5.6's worked listing is compared against this output on every build. That
check exists because the spec's listings were hand-written and drifted: an extra
branch and a pessimistic register count both passed the internal-consistency
checker, which by construction could not notice.

## 5. The binary

{ninstr} instructions in {nbytes} bytes. Each length comes from bits `[1:0]` of
its first halfword alone — this walker never looks at the format tag, which is
exactly what §2 claims.

```
{hexd}
```

{nbytes} bytes against {ninstr * 4} for a fixed-32 encoding.

### Two instructions, field by field

The O-24 bootstrap, decoded from the real bytes using the §3 bit map:

```
{dec_por}
```

`ps0 = 4` is `!P0` — bit 2 of a qualifier is the negate bit — and `ps1 = 0` is
`P0`. So this is `por p0, !p0, p0`: all-ones whatever `P0` held, in 16 bits.

And the 48-bit constant:

```
{dec_f48}
```

## 6. Disassembly and execution

The simulator drives the *generated* disassembler, so this is the encoding read
back by a different TableGen backend than the one that wrote it. This run has
20 of 32 threads active, so the guard actually diverges. The mask column is the
set of lanes issuing together.

```
{trace}
```

The mask is `ffffffff` through the prologue, narrows to `000fffff` for the body,
and is `ffffffff` again at `exit`. Lanes regroup because their PCs coincide —
there is no bracket instruction and nothing forces it (§1).

## 7. Result

```
{e2e}
```

`c[i] = a[i] + b[i]` verified as FP32 bit patterns across all 32 lanes at four
divergence levels. Inactive lanes are checked to be *untouched*: `c[]` is
poisoned before each run, so a lane that executed when it should not have would
fail rather than coincidentally agree.

`n=0` is the case where every lane takes the guard and the body is skipped, which
is why its issue-group count is lower.
"""
open("docs/walkthrough.md","w").write(doc)
print(f"  wrote docs/walkthrough.md ({len(doc.splitlines())} lines)")
