#!/usr/bin/env python3
"""
Emit CCGOperandWidths.inc from TableGen JSON: for each instruction, the bit
width of every encoded operand field.

The round-trip tool needs this. An immediate wider than its field is truncated
by the encoder, so the decode would legitimately disagree and the test would
report a failure that is not one. Widths come from the same .td the encoder
does, so the test exercises encoder against decoder -- two different TableGen
backends -- rather than either against itself.
"""
import json, sys
from collections import defaultdict

recs = json.load(open(sys.argv[1]))
insts = {k: v for k, v in recs.items()
         if isinstance(v, dict) and "Inst" in v and isinstance(v.get("Size"), int)
         and v["Size"] > 0 and "CCGInst" in v.get("!superclasses", [])}

out = ["// Generated by tools/gen-operand-widths.py -- do not edit.",
       "// Maps each instruction's encoded operand fields to their bit widths.",
       "struct CCGFieldWidth { const char *Var; unsigned Bits; };",
       "struct CCGInstFields { const char *Inst; unsigned NumFields;",
       "                       const CCGFieldWidth *Fields; };", ""]

tables, index = [], []
for name in sorted(insts):
    w = defaultdict(int)
    for b in insts[name]["Inst"]:
        if isinstance(b, dict) and b.get("kind") == "varbit":
            w[b["var"]] += 1
    if not w:
        index.append(f'  {{"{name}", 0, nullptr}},')
        continue
    entries = ", ".join(f'{{"{v}", {n}}}' for v, n in sorted(w.items()))
    tables.append(f"static const CCGFieldWidth Fields_{name}[] = {{{entries}}};")
    index.append(f'  {{"{name}", {len(w)}, Fields_{name}}},')

out += tables + ["", "static const CCGInstFields CCGInstFieldTable[] = {"] + index + ["};"]
out.append(f"static const unsigned CCGNumInstFields = {len(index)};")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(f"  wrote {len(index)} instruction field tables")
