#!/usr/bin/env python3
"""
Emit CCVOperandWidths.inc from TableGen JSON: for each instruction, in MCInst
operand order, the width of the field each operand is encoded into and whether
that field is signed.

The round-trip tool needs this. An immediate wider than its field is truncated
by the encoder, so the decode would legitimately disagree and the test would
report a failure that is not one. Widths come from the same .td the encoder
does, so the test exercises encoder against decoder -- two different TableGen
backends -- rather than either against itself.
"""
import json, sys
from collections import defaultdict

recs = json.load(open(sys.argv[1]))
insts = {k: v for k, v in recs.items()
         if isinstance(v, dict) and "Inst" in v and isinstance(v.get("Size"), int)
         and v["Size"] > 0 and "CCVInst" in v.get("!superclasses", [])}

out = ["// Generated by tools/gen-operand-widths.py -- do not edit.",
       "// Per-instruction operand info, in MCInst operand order (outs then ins):",
       "// the width of the field each operand is encoded into, and whether that",
       "// field is signed. Operands that are not encoded fields get width 0.",
       "struct CCVOperandInfo { unsigned Bits; bool Signed; };",
       "struct CCVInstOperands { const char *Inst; unsigned NumOperands;",
       "                         const CCVOperandInfo *Operands; };", ""]

SIGNED_PREFIXES = ("simm", "brtarget")

def operand_list(rec):
    """(name, class) in MCInst order: outs first, then ins."""
    seq = []
    for key in ("OutOperandList", "InOperandList"):
        for arg in rec.get(key, {}).get("args", []):
            cls, nm = arg[0], arg[1]
            seq.append((nm, cls.get("def", "") if isinstance(cls, dict) else ""))
    return seq

tables, index = [], []
for name in sorted(insts):
    w = defaultdict(int)
    for b in insts[name]["Inst"]:
        if isinstance(b, dict) and b.get("kind") == "varbit":
            w[b["var"]] += 1
    ops = operand_list(insts[name])
    if not ops:
        index.append(f'  {{"{name}", 0, nullptr}},')
        continue
    entries = ", ".join(
        "{%d, %s}" % (w.get(nm, 0),
                      "true" if cls.startswith(SIGNED_PREFIXES) else "false")
        for nm, cls in ops)
    tables.append(f"static const CCVOperandInfo Operands_{name}[] = {{{entries}}};")
    index.append(f'  {{"{name}", {len(ops)}, Operands_{name}}},')

out += tables + ["", "static const CCVInstOperands CCVInstOperandTable[] = {"] + index + ["};"]
out.append(f"static const unsigned CCVNumInstOperands = {len(index)};")
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print(f"  wrote {len(index)} instruction operand tables")
